buildec.yml for sonar

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -6,32 +6,14 @@ phases:
       python: 3.11
     commands:
       - pip install --upgrade pip
-      - pip install -r requirements.txt
-      - pip install pylint
-      
-      # Check if Sonar Scanner is installed, if not, download and install it
-      - |
-        if [ ! -x "$(command -v sonar-scanner)" ]; then
-          echo "Sonar Scanner not found. Installing..."
-          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip &&
-          unzip sonar-scanner-cli-4.6.2.2472-linux.zip &&
-          export PATH=$PATH:./sonar-scanner-cli-4.6.2.2472-linux/bin/
-        fi
+      - pip install -r requirements.txt  # Install project dependencies
+      - pip install pylint  # Install pylint for static code analysis
 
   pre_build:
     commands:
-      - python --version
-      - pylint $CODEBUILD_SRC_DIR/manage.py || true
-
-  build:
-    commands:
-      - sonar-scanner \
-          -Dsonar.projectKey="azharakhter555" \
-          -Dsonar.organization="azharakhter555" \
-          -Dsonar.host.url="https://sonarcloud.io" \
-          -Dsonar.login="dfb96a75ff67413791f60ca1b049976beccfaec6" \
-          -X
+      - python --version  # Print Python version for verification
+      - pylint $CODEBUILD_SRC_DIR/manage.py || true  # Run pylint on manage.py and ignore exit status
 
 artifacts:
   files:
-    - '**/*'
+    - '**/*'  # Include all files in the artifact
