buildec.yml for sonar

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -8,12 +8,41 @@ phases:
       - pip install --upgrade pip
       - pip install -r requirements.txt  # Install project dependencies
       - pip install pylint  # Install pylint for static code analysis
+      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
+      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
+      - export PATH=$PATH:./sonar-scanner-cli-4.6.2.2472-linux/bin/
 
   pre_build:
     commands:
       - python --version  # Print Python version for verification
       - pylint $CODEBUILD_SRC_DIR/manage.py || true  # Run pylint on manage.py and ignore exit status
 
+  build:
+  commands:
+    - |
+      if [ -z "$Project" ]; then
+          echo "Error: SonarCloud project key not found."
+          exit 1
+      fi
+      if [ -z "$Organization" ]; then
+          echo "Error: SonarCloud organization key not found."
+          exit 1
+      fi
+      if [ -z "$HOST" ]; then
+          echo "Error: SonarCloud host URL not found."
+          exit 1
+      fi
+      if [ -z "$LOGIN" ]; then
+          echo "Error: SonarCloud login token not found."
+          exit 1
+      fi
+      
+      sonar-scanner \
+          -Dsonar.projectKey="$Project" \
+          -Dsonar.organization="$Organization" \
+          -Dsonar.host.url="$HOST" \
+          -Dsonar.login="$LOGIN" \
+          -X  # Verbose output for debugging purposes
 artifacts:
   files:
     - '**/*'  # Include all files in the artifact
